### ISSUE TITLE
Sidepanel still missing from some of the pages.

### ISSUE THREAD

**Issue by Megalomaniak** [TwistedTwigleg/vanilla-bootstrap#19]
User profile page for an example. There might be others too, might have to try and look through every page, just to make sure. In some cases perhaps its not really necessary though. Would still need to validate that assumption!

**Comment by TwistedTwigleg** [comment]
Rats, I thought we got all of the pages!

> There might be others too, might have to try and look through every page, just to make sure. In some cases perhaps its not really necessary though. Would still need to validate that assumption!

I’ll try to look through the pages soon to see if I can spot any others.

**Comment by Megalomaniak** [comment]
It might be useful to separate the sidepanel conditionals into another smarty file and include them in the master through inheritance perhaps:

[Template Inheritance](https://www.smarty.net/docs/en/advanced.features.template.inheritance.tpl)

Actually on closer inspection looks like [include](https://www.smarty.net/docs/en/language.function.include.tpl) would be more useful in this case, since inheritance seems to be a build related thing which is probably something we do not want to deal with at all in our case.

Do note that smarty is still a bit of a mystery to me too, so I might be a bit confused about things here myself.

**Comment by TwistedTwigleg** [comment]
Okay, I added the sidebar to both the profile/user pages and to the private discussion pages. Hopefully now it *should* be everywhere.

> It might be useful to separate the sidepanel conditionals into another smarty file and include them in the master through inheritance perhaps:
> 
> [Template Inheritance](https://www.smarty.net/docs/en/advanced.features.template.inheritance.tpl)
> 
> Actually on closer inspection looks like [include](https://www.smarty.net/docs/en/language.function.include.tpl) would be more useful in this case, since inheritance seems to be a build related thing which is probably something we do not want to deal with at all in our case.
> 
> Do note that smarty is still a bit of a mystery to me too, so I might be a bit confused about things here myself.

Good idea! That way we can keep things a little better separated for better management. Looking at the includes, it doesn't look like it should be too difficult.

And yeah, Smarty is still a mystery to me too. 😅

**Comment by TwistedTwigleg** [comment]
I just pushed a commit that moves the Smarty stuff for the side panel to itself own file. Now it should be a little bit easier to maintain.

When you have a chance (no rush) and if you do not mind, can you take a look to make sure it is working on your end?

**Comment by Megalomaniak** [comment]
Seems to be working. I just disabled the rich editor too, however the advanced editor is not showing up, just a plain text area and no buttons for formatting or anything. Trying to preview the message gives a invisible error message(white text on white background). Might have to open an issue to track it and try and fix that then.

**Comment by TwistedTwigleg** [comment]
> Seems to be working.

Great! I was hoping it would work, but with my limited knowledge of Smarty I didn't want to assume. Thanks for checking!

Do you think we should we close this issue or should we leave it open in so we can post to it if we discover the side panel is missing somewhere?

**Comment by Megalomaniak** [comment]
Well, some elements of the side panel are still missing, on profile page there is now no way to change the user image/avatar anymore. But then maybe we should customize the main content area to include such things instead.

**Comment by TwistedTwigleg** [comment]
> Well, some elements of the side panel are still missing, on profile page there is now no way to change the user image/avatar anymore. But then maybe we should customize the main content area to include such things instead.

Okay, in that case we should leave this open. As for the side menu for changing the user image/avatar, I'll try to look into it and see if I can add it later today, so it is there at least for the short term, since I imagine customizing the main content area will take a bit.

**Comment by Megalomaniak** [comment]
> ...since I imagine customizing the main content area will take a bit.

Yeah, while an interesting idea, probably best left for the future.

**Comment by Megalomaniak** [comment]
Seems the private messages are still missing it too.

**Comment by TwistedTwigleg** [comment]
> Seems the private messages are still missing it too.

Thanks! I just fixed it.

Unfortunately, the only way I could find to fix it was to use `{asset name="Panel"}`, since the conversation module apparently injects javascript code or something. Adding the modules individually like we are doing for the rest of the side panel wasn't working.

This means we won't be able to add any collapsible elements for private conversations, but I figure it is better than nothing. I might try to look into this more later, but in an effort to get things working sooner rather than later, I figure we can just use `{asset name="Panel"}` for now.

**Comment by Megalomaniak** [comment]
Yeah, I think for the conversations it is fine.

**Comment by Megalomaniak** [comment]
Probably time to close this.
